Repository atlassian/react-beautiful-dnd, pull requests merged in 2018-07, with the labels that each got.

#612 pulling getSpeed function out
  src/view/draggable/draggable.jsx
Labels: engineering health 🛠

#619 SVG warnings. Closes #613
  .size-snapshot.json
  docs/guides/dragging-svgs.md
  docs/guides/using-inner-ref.md
  src/view/drag-handle/drag-handle.jsx
  src/view/drag-handle/util/get-drag-handle-ref.js
  src/view/draggable/draggable.jsx
  src/view/throw-if-invalid-inner-ref.js
  test/unit/view/drag-handle/throw-if-svg.spec.js
Labels: docs 📖, engineering health 🛠

#627 Draggable refactor
  .size-snapshot.json
  src/state/create-store.js
  src/view/drag-handle/drag-handle-types.js
  src/view/drag-handle/drag-handle.jsx
  src/view/drag-handle/util/get-drag-handle-ref.js
  src/view/draggable/draggable.jsx
  test/unit/view/drag-handle/ touch-sensor.spec.js
  test/unit/view/drag-handle/attributes.spec.js
  test/unit/view/drag-handle/block-drag-start-when-something-else-dragging.spec.js
  test/unit/view/drag-handle/contenteditable.spec.js
  test/unit/view/drag-handle/disabled-while-capturing.spec.js
  test/unit/view/drag-handle/disabled.spec.js
  test/unit/view/drag-handle/drag-handle.spec.js
  test/unit/view/drag-handle/focus-management.spec.js
  test/unit/view/drag-handle/interactive-elements.spec.js
  test/unit/view/drag-handle/keyboard-sensor.spec.js
  test/unit/view/drag-handle/mouse-sensor.spec.js
  test/unit/view/drag-handle/nested-drag-handles.spec.js
  test/unit/view/drag-handle/page-visibility-changes.spec.js
  test/unit/view/drag-handle/throw-if-svg.spec.js
  test/unit/view/drag-handle/util/basic-context.js
  test/unit/view/drag-handle/util/callbacks.js
  test/unit/view/drag-handle/util/controls.js
  test/unit/view/drag-handle/util/events.js
  test/unit/view/drag-handle/util/wrappers.js
  test/unit/view/drag-handle/window-bindings.spec.js
  test/unit/view/unconnected-draggable.spec.js
Labels: engineering health 🛠

#629 Broader prettier
  docs/guides/how-we-use-dom-events.md
  docs/guides/screen-reader.md
  docs/patterns/multi-drag.md
  docs/patterns/tables.md
  docs/patterns/using-a-portal.md
  package.json
Labels: engineering health 🛠

#643 bumping raf-schd
  package.json
  yarn.lock
Labels: engineering health 🛠

#639 Updated README.md with valid sandbox url
  README.md
Labels: docs 📖

#662 Adding more detail to droppable optimisation. Closes #660
  README.md
Labels: docs 📖
